parameters:
#    dw_comments.example.class: DW\CommentsBundle\Example

services:
#    dw_comments.example:
#        class: %dw_comments.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
